# Generated by Django 4.2.18 on 2025-01-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Movies',
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='Rooms',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='room_id',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='room_name',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='movie_id',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='movie_name',
            new_name='room_name',
        ),
    ]
