# Generated by Django 4.2.18 on 2025-01-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='is_reserved',
        ),
    ]
